In [27]:
from keras.preprocessing.image import ImageDataGenerator
from skimage import io

# Construct an instance of the ImageDataGenerator class
# Pass the augmentation parameters through the constructor. 

datagen = ImageDataGenerator( 
        width_shift_range=0,   #% shift
        height_shift_range=0,
        zoom_range=0.3,
        horizontal_flip=False,
        fill_mode='constant', cval=125)    #Also try nearest, constant, reflect, wrap

In [22]:
####################################################################
#Multiple images.
#Manually read each image and create an array to be supplied to datagen via flow method
dataset = []

import numpy as np
from skimage import io
import os
from PIL import Image

image_directory = 'aug/'
SIZE = 256
dataset = []



In [28]:
my_images = os.listdir(image_directory)
for i, image_name in enumerate(my_images):
        image = io.imread(image_directory + image_name)
        image = Image.fromarray(image, 'RGB')
        # image = image.resize((SIZE,SIZE))
        dataset.append(np.array(image))

x = np.array(dataset)

In [24]:
print(x)

[[[[139 131 120]
   [140 132 121]
   [139 131 120]
   ...
   [164 158 149]
   [163 159 149]
   [163 159 149]]

  [[139 131 120]
   [139 131 120]
   [140 132 121]
   ...
   [164 158 149]
   [163 159 149]
   [163 159 149]]

  [[139 131 120]
   [139 131 120]
   [141 133 122]
   ...
   [164 158 149]
   [163 159 149]
   [163 159 149]]

  ...

  [[135 127 116]
   [135 127 116]
   [136 128 117]
   ...
   [154 146 135]
   [155 147 136]
   [156 148 137]]

  [[136 126 114]
   [136 126 114]
   [137 127 117]
   ...
   [152 147 135]
   [152 147 135]
   [153 148 136]]

  [[136 126 114]
   [136 126 114]
   [137 127 117]
   ...
   [151 146 134]
   [151 146 134]
   [151 146 134]]]]


In [29]:
i = 0
for batch in datagen.flow(x, batch_size=16,  
                          save_to_dir='after_augmentation', 
                          save_prefix='aug', 
                          save_format='png'):
    i += 1
    if i > 20:
        break

In [25]:
# #####################################################################
# #Multiclass. Read dirctly from the folder structure using flow_from_directory
# # We do not use it since it does do mirror images

# i = 0
# for batch in datagen.flow_from_directory(directory='aug/',
#                                          #target_size=(256, 256),
#                                          color_mode="rgb",
#                                          save_to_dir='after_augmentation/', 
#                                          save_prefix='aug', 
#                                          save_format='png'):
#     i += 1
#     if i > 15:
#         break 

Found 0 images belonging to 0 classes.
